# Generated by Django 5.1.7 on 2025-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('series', 'Series'), ('movie', 'Movie')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('vector', models.TextField()),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(max_length=255)),
            ],
        ),
    ]
